version: '3.7'

networks:
  overlay-net:
          external: true
          driver: overlay

services:

  cat:
    image: iudx/cat-prod:latest
    environment:
      - CAT_URL=https://api.catalogue.iudx.io
      - LOG_LEVEL=INFO
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./docs/:/usr/share/app/docs
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./ui/dist/:/usr/share/app/ui/dist
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -jar  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory ./fatjar.jar -c configs/config.json"

  dev:
    image: iudx/cat-dev:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=DEBUG
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./ui/dist/:/usr/share/app/ui/dist
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: "java -jar ./fatjar.jar -c configs/config.json"

  
  test:
    image: iudx/cat-test:latest
    environment:
      - CAT_URL=https://catalogue.iudx.org.in
      - LOG_LEVEL=INFO
    volumes:
      - ./src/:/usr/share/app/src
      - ./configs/config-test.json:/usr/share/app/configs/config-test.json
      - /tmp/test:/tmp/test
      
    command: bash -c "mvn clean test -Dtest=IntegrationTest && cp -r target /tmp/test"


    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"



  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - overlay-net
