version: '3.7'

networks:
  profanity-check-net:
    driver: bridge


services:
  profanity-check:
    image: ghcr.io/datakaveri/profanity-check-sdk:4.0.0-5 
    volumes:
      - ./config.json:/usr/share/app/config.json
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - profanity-check-net
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "5"
